<a href="https://colab.research.google.com/github/Jayed096/CementStrength-Prediction/blob/main/Jayed_Preprocessing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import iplot

In [ ]:
import nltk
from nltk.stem import PorterStemmer
import re
import string
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from wordcloud import WordCloud, STOPWORDS
from string import punctuation
from bs4 import BeautifulSoup
import re,string,unicodedata
from nltk import pos_tag
from nltk.corpus import wordnet, stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/training_set_rel3.tsv",sep='\t', encoding='ISO-8859-1')

In [ ]:
df.head()

   essay_id  essay_set  ... rater3_trait5  rater3_trait6
0         1          1  ...           NaN            NaN
1         2          1  ...           NaN            NaN
2         3          1  ...           NaN            NaN
3         4          1  ...           NaN            NaN
4         5          1  ...           NaN            NaN

[5 rows x 28 columns]

In [ ]:
df.shape

(12976, 28)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12976 entries, 0 to 12975
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   essay_id        12976 non-null  int64
 1   essay_set       12976 non-null  int64
 2   essay           12976 non-null  object
 3   rater1_domain1  12976 non-null  int64
 4   rater2_domain1  12976 non-null  int64
 5   rater3_domain1  128 non-null    float64
 6   domain1_score   12976 non-null  int64
 7   rater1_domain2  1800 non-null   float64
 8   rater2_domain2  1800 non-null   float64
 9   domain2_score   1800 non-null   float64
 10  rater1_trait1   2292 non-null   float64
 11  rater1_trait2   2292 non-null   float64
 12  rater1_trait3   2292 non-null   float64
 13  rater1_trait4   2292 non-null   float64
 14  rater1_trait5   723 non-null    float64
 15  rater1_trait6   723 non-null    float64
 16  rater2_trait1   2292 non-null   float64
 17  rater2_trait2   2292 non-null   float64
 18  rater2_trait3   2292 non-null   float64
 19  rater2_trait4   2292 non-null   float64
 20  rater2_trait5   723 non-null    float64
 21  rater2_trait6   723 non-null    float64
 22  rater3_trait1   128 non-null    float64
 23  rater3_trait2   128 non-null    float64
 24  rater3_trait3   128 non-null    float64
 25  rater3_trait4   128 non-null    float64
 26  rater3_trait5   128 non-null    float64
 27  rater3_trait6   128 non-null    float64
dtypes: float64(22), int64(5), object(1)
memory usage: 2.8+ MB

In [ ]:
df.isnull().sum()

essay_id              0
essay_set             0
essay                 0
rater1_domain1        0
rater2_domain1        0
rater3_domain1    12848
domain1_score         0
rater1_domain2    11176
rater2_domain2    11176
domain2_score     11176
rater1_trait1     10684
rater1_trait2     10684
rater1_trait3     10684
rater1_trait4     10684
rater1_trait5     12253
rater1_trait6     12253
rater2_trait1     10684
rater2_trait2     10684
rater2_trait3     10684
rater2_trait4     10684
rater2_trait5     12253
rater2_trait6     12253
rater3_trait1     12848
rater3_trait2     12848
rater3_trait3     12848
rater3_trait4     12848
rater3_trait5     12848
rater3_trait6     12848
dtype: int64

In [ ]:
df.dropna(axis = 1, inplace = True)
df.head()

   essay_id  essay_set  ... rater2_domain1  domain1_score
0         1          1  ...              4              8
1         2          1  ...              4              9
2         3          1  ...              3              7
3         4          1  ...              5             10
4         5          1  ...              4              8

[5 rows x 6 columns]

In [ ]:
df.head()

   essay_id  essay_set  ... rater2_domain1  domain1_score
0         1          1  ...              4              8
1         2          1  ...              4              9
2         3          1  ...              3              7
3         4          1  ...              5             10
4         5          1  ...              4              8

[5 rows x 6 columns]

In [ ]:
df['essay']

0        Dear local newspaper, I think effects computer...
1        Dear @CAPS1 @CAPS2, I believe that using compu...
2        Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...
3        Dear Local Newspaper, @CAPS1 I have found that...
4        Dear @LOCATION1, I know having computers has a...
                               ...
12971     In most stories mothers and daughters are eit...
12972     I never understood the meaning laughter is th...
12973    When you laugh, is @CAPS5 out of habit, or is ...
12974                                   Trippin' on fen...
12975     Many people believe that laughter can improve...
Name: essay, Length: 12976, dtype: object

In [ ]:
from nltk.tokenize import sent_tokenize

df_words = df['essay'].apply(sent_tokenize)
df_words.head()

0    [Dear local newspaper, I think effects compute...
1    [Dear @CAPS1 @CAPS2, I believe that using comp...
2    [Dear, @CAPS1 @CAPS2 @CAPS3 More and more peop...
3    [Dear Local Newspaper, @CAPS1 I have found tha...
4    [Dear @LOCATION1, I know having computers has ...
Name: essay, dtype: object

In [ ]:
from nltk.tokenize import word_tokenize
df_words = df['essay'].apply(word_tokenize)
df_words.head()

0    [Dear, local, newspaper, ,, I, think, effects,...
1    [Dear, @, CAPS1, @, CAPS2, ,, I, believe, that...
2    [Dear, ,, @, CAPS1, @, CAPS2, @, CAPS3, More, ...
3    [Dear, Local, Newspaper, ,, @, CAPS1, I, have,...
4    [Dear, @, LOCATION1, ,, I, know, having, compu...
Name: essay, dtype: object

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
from nltk.stem import WordNetLemmatizer
ps = WordNetLemmatizer()
corps = []
for i in range(0, len(df_words)):
    review = re.sub('[^a-zA-Z]', ' ', str(df_words[i]))
    review = review.lower()
    review = review.split()
    review = [ps.lemmatize(word) for word in review if not word in stopwords.words('english')] 
    review = ' '.join(review)
    corps.append(review)

In [ ]:
corps[1]

'dear cap cap believe using computer benefit u many way like talking becoming friend others website like facebook mysace using computer help u find coordibates location able ourselfs million information also computer benefit u helping job planning house plan typing num page report one job le writing let go wonder world technology using computer help u life talking making friend line many people myspace facebooks aim benefit u conversation one another many people believe computer bad make friend never talk fortunate computer help school work social life make friend computer help u finding location coordibates million information online n go internet lot would n know go onto website month help u location coordinate like location would rather use computer location supposed vacationing location million information found internet almost every question computer would rather easily draw house plan computer take num hour one hand ugly erazer mark garrenteed find job drawing like also appling job many worker must write long paper like num word essay job fit many people know n like writing num word non stopp hour could take hav computer computer needed lot adays hope essay impacted descion computer great machine work day showed mom use computer said greatest invention sense sliced bread go buy computer help chat online friend find location million information one click button help self getting job neat prepared printed work bos love'

In [ ]:
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english') # To find list of stop words of english

word_frequencies = {}

for word in nltk.word_tokenize(str(corps)):
    if word not in stopwords:
        if word not in word_frequencies.keys():
            word_frequencies[word] = 1
        else:
            word_frequencies[word]+=1

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
word_frequencies

{'[': 1,
 "'dear": 1236,
 'local': 668,
 'newspaper': 853,
 'think': 7748,
 'effect': 1939,
 'computer': 19992,
 'people': 21110,
 'great': 2549,
 'learning': 760,
 'skill': 585,
 'affect': 1624,
 'give': 2531,
 'u': 4805,
 'time': 11160,
 'chat': 679,
 'friend': 6767,
 'new': 4228,
 'help': 4466,
 'learn': 2803,
 'globe': 46,
 'astronomy': 1,
 'keep': 2260,
 'troble': 9,
 'thing': 10588,
 'dont': 1464,
 'would': 15042,
 'feel': 2741,
 'teenager': 395,
 'always': 3480,
 'phone': 769,
 'ever': 1913,
 'buisness': 76,
 'partner': 52,
 'well': 2347,
 'way': 6882,
 'plenty': 115,
 'site': 432,
 'internet': 1508,
 'organization': 3566,
 'cap': 36521,
 'facebook': 530,
 'myspace': 244,
 'ect': 190,
 'setting': 2261,
 'meeting': 167,
 'bos': 62,
 'fun': 1737,
 'rushing': 82,
 'get': 9666,
 'cause': 1373,
 'want': 5432,
 'use': 3770,
 'country': 1447,
 'state': 5048,
 'outside': 1575,
 'going': 4828,
 'might': 1919,
 'child': 5480,
 'spends': 64,
 'lot': 2856,
 'ask': 690,
 'question': 563,
 'economy': 60,
 'sea': 24,
 'floor': 235,
 'spreading': 15,
 'even': 5630,
 'date': 1973,
 'surprise': 59,
 'much': 4082,
 'know': 5540,
 'believe': 2328,
 'interesting': 315,
 'class': 815,
 'day': 5151,
 'reading': 1898,
 'book': 13902,
 'home': 4352,
 'library': 7131,
 'better': 2324,
 'fresh': 243,
 'perpressured': 1,
 'something': 4195,
 'isnt': 67,
 'right': 3281,
 'forbidde': 1,
 'hospital': 79,
 'bed': 274,
 'drive': 298,
 'rather': 786,
 'chatting': 151,
 'playing': 815,
 'game': 2271,
 'safe': 684,
 'sound': 363,
 'community': 441,
 'place': 3209,
 'hope': 1276,
 'reached': 171,
 'point': 1098,
 'understand': 808,
 'agree': 864,
 'thank': 324,
 'listening': 347,
 "'": 12976,
 ',': 12975,
 'using': 1229,
 'benefit': 761,
 'many': 6822,
 'like': 10462,
 'talking': 1342,
 'becoming': 277,
 'others': 1569,
 'website': 1029,
 'mysace': 1,
 'find': 3887,
 'coordibates': 2,
 'location': 3822,
 'able': 2275,
 'ourselfs': 9,
 'million': 219,
 'information': 1879,
 'also': 8066,
 'helping': 282,
 'job': 1067,
 'planning': 83,
 'house': 2384,
 'plan': 484,
 'typing': 287,
 'num': 7263,
 'page': 230,
 'report': 275,
 'one': 10091,
 'le': 1017,
 'writing': 624,
 'let': 2118,
 'go': 7511,
 'wonder': 177,
 'world': 3347,
 'technology': 927,
 'life': 6654,
 'making': 1210,
 'line': 1151,
 'facebooks': 7,
 'aim': 76,
 'conversation': 219,
 'another': 3724,
 'bad': 3144,
 'make': 6519,
 'never': 2896,
 'talk': 3235,
 'fortunate': 18,
 'school': 3183,
 'work': 2482,
 'social': 518,
 'finding': 285,
 'online': 1781,
 'n': 12634,
 'onto': 271,
 'month': 3331,
 'coordinate': 6,
 'supposed': 185,
 'vacationing': 2,
 'found': 1672,
 'almost': 1186,
 'every': 2228,
 'easily': 421,
 'draw': 88,
 'take': 5208,
 'hour': 1967,
 'hand': 1932,
 'ugly': 23,
 'erazer': 1,
 'mark': 41,
 'garrenteed': 1,
 'drawing': 32,
 'appling': 2,
 'worker': 270,
 'must': 587,
 'write': 675,
 'long': 1949,
 'paper': 719,
 'word': 1515,
 'essay': 469,
 'fit': 294,
 'non': 152,
 'stopp': 1,
 'could': 8775,
 'hav': 22,
 'needed': 849,
 'adays': 10,
 'impacted': 20,
 'descion': 1,
 'machine': 107,
 'showed': 370,
 'mom': 2171,
 'said': 4110,
 'greatest': 472,
 'invention': 126,
 'sense': 577,
 'sliced': 3,
 'bread': 11,
 'buy': 609,
 'click': 204,
 'button': 109,
 'self': 558,
 'getting': 1754,
 'neat': 44,
 'prepared': 82,
 'printed': 16,
 'love': 2847,
 'everyone': 2895,
 'agrees': 65,
 'society': 1654,
 'support': 365,
 'advance': 250,
 'positive': 1117,
 'different': 2709,
 'idea': 1692,
 'amount': 456,
 'today': 1212,
 'spme': 1,
 'man': 665,
 'accomplishment': 16,
 'helpful': 517,
 'news': 436,
 'live': 1165,
 'stream': 25,
 'wrong': 1129,
 'spend': 1319,
 'interacting': 249,
 'tell': 1940,
 'grow': 416,
 'author': 4781,
 'journalist': 6,
 'fact': 1078,
 'involve': 53,
 'exactly': 257,
 'expert': 229,
 'spending': 668,
 'exercising': 413,
 'enjoying': 354,
 'nature': 1667,
 'family': 6838,
 'living': 451,
 'choose': 431,
 'honest': 107,
 'concern': 222,
 'called': 785,
 'interact': 321,
 'thousand': 737,
 'kid': 4049,
 'street': 426,
 'instead': 1141,
 'causing': 183,
 'trouble': 454,
 'locate': 16,
 'wanted': 1516,
 'criminal': 41,
 'see': 4716,
 'useful': 287,
 'say': 5590,
 'benifit': 134,
 'case': 402,
 'true': 575,
 'studdies': 1,
 'show': 3248,
 'nothing': 1321,
 'beat': 160,
 'person': 9498,
 'really': 3455,
 'close': 901,
 'example': 2721,
 'webcam': 144,
 'e': 285,
 'mail': 360,
 'percent': 1002,
 'student': 1221,
 'good': 5033,
 'grade': 626,
 'refer': 13,
 'reliable': 46,
 'reasearch': 33,
 'catalouges': 1,
 'advertisments': 4,
 'store': 831,
 'worldwide': 20,
 'allowed': 544,
 'modern': 170,
 'exist': 67,
 'best': 1507,
 'form': 390,
 'communication': 431,
 'ability': 536,
 'back': 3997,
 'cheaper': 21,
 'single': 394,
 'event': 301,
 'planed': 12,
 'need': 4067,
 'homework': 678,
 'lam': 1,
 'sick': 172,
 'studying': 72,
 'test': 2693,
 'contact': 254,
 'teacher': 789,
 'post': 101,
 'office': 226,
 'us': 352,
 'letter': 360,
 'box': 133,
 'president': 58,
 'imposible': 13,
 'coustmers': 1,
 'telling': 433,
 'zip': 7,
 'code': 9,
 'heavy': 97,
 'happening': 228,
 'around': 3479,
 'moder': 2,
 'provid': 1,
 'commucated': 1,
 'quick': 153,
 'took': 1293,
 'pole': 74,
 'used': 1986,
 'type': 1585,
 'currently': 28,
 'survey': 74,
 'taken': 1252,
 'fore': 20,
 'reason': 4144,
 'posible': 4,
 'access': 277,
 'document': 87,
 'probably': 660,
 'gotten': 237,
 'assignment': 133,
 'amagine': 2,
 'suddenly': 125,
 'reporter': 10,
 'article': 472,
 'occur': 72,
 'buissness': 20,
 'including': 157,
 'advertise': 10,
 'shop': 258,
 'read': 4611,
 'association': 2,
 'reported': 20,
 'position': 74,
 'import': 9,
 'catalouge': 1,
 'promote': 37,
 'save': 354,
 'tree': 274,
 'castomer': 1,
 'convinence': 2,
 'small': 486,
 'explain': 234,
 'star': 85,
 'potential': 88,
 'coustomers': 1,
 'owner': 259,
 'saved': 105,
 'resturant': 9,
 'wer': 23,
 'jobless': 1,
 'conclusion': 1051,
 'everyday': 668,
 'without': 1844,
 'convinences': 1,
 'communicate': 516,
 'reaserch': 12,
 'subject': 438,
 'current': 816,
 'moderation': 26,
 'tool': 204,
 'connect': 209,
 'contain': 200,
 'education': 352,
 'conveint': 1,
 'computors': 48,
 'step': 263,
 'future': 602,
 'advantage': 117,
 'first': 3202,
 'member': 407,
 'away': 2813,
 'car': 1027,
 'includes': 106,
 'sitting': 617,
 'calling': 133,
 'everywhere': 206,
 'board': 134,
 'easier': 600,
 'easy': 670,
 'last': 1654,
 'kind': 1369,
 'activity': 314,
 'number': 321,
 'together': 1367,
 'bringing': 76,
 'tip': 67,
 'finger': 131,
 'try': 1406,
 'mae': 4,
 'secondly': 252,
 'collage': 31,
 'ar': 57,
 'miss': 293,
 'anything': 1680,
 'material': 2870,
 'missed': 154,
 'lastly': 717,
 'classroom': 82,
 'ca': 1034,
 'afford': 63,
 'hard': 1816,
 'change': 1151,
 'lean': 18,
 'far': 863,
 'result': 242,
 'improve': 157,
 'convience': 1,
 'crazy': 231,
 'someone': 3094,
 'wo': 371,
 'offer': 197,
 'confrence': 2,
 'parttners': 1,
 'lighter': 39,
 'nation': 109,
 'conviente': 2,
 'subssiquently': 1,
 'flight': 99,
 'vacation': 208,
 'rental': 25,
 'nice': 586,
 'negative': 569,
 'ace': 33,
 'camputer': 1,
 'daily': 240,
 'america': 107,
 'least': 548,
 'mean': 1898,
 'cant': 390,
 'exercise': 830,
 'wasting': 79,
 'posibility': 3,
 'physical': 141,
 'everything': 1793,
 'done': 1284,
 'got': 3991,
 'sit': 647,
 'put': 2107,
 'mailbox': 3,
 'walk': 674,
 'email': 423,
 'sitdown': 1,
 'move': 631,
 'difference': 165,
 'er': 9,
 'literally': 49,
 'add': 624,
 'lead': 677,
 'everthing': 18,
 'wouldbe': 1,
 'gone': 449,
 'phisically': 3,
 'hurt': 599,
 'happened': 705,
 'grandpa': 120,
 'wood': 90,
 'chair': 167,
 'ardthritis': 1,
 'muscle': 58,
 'th': 49,
 "'know": 31,
 'depending': 77,
 'safety': 804,
 'natural': 113,
 'opinion': 1459,
 'increasing': 38,
 'benefiting': 26,
 'initially': 8,
 'risk': 281,
 'begin': 373,
 'end': 1739,
 'girl': 1090,
 'began': 474,
 'predator': 38,
 'unless': 178,
 'meet': 451,
 'somewhere': 241,
 'maybe': 922,
 'late': 260,
 'moreover': 27,
 'study': 396,
 'widely': 9,
 'exposed': 200,
 'year': 1940,
 'due': 1057,
 'share': 261,
 'finally': 1590,
 'stop': 1192,
 'order': 510,
 'furthermore': 110,
 'full': 407,
 'immense': 19,
 'landscape': 36,
 'wide': 196,
 'water': 2842,
 'dense': 13,
 'forest': 37,
 'lush': 11,
 'valley': 5,
 'depend': 54,
 'teach': 933,
 'cease': 8,
 'actually': 607,
 'experiencing': 29,
 'smell': 105,
 'taste': 126,
 'recent': 138,
 'went': 2639,
 'grand': 47,
 'canyon': 5,
 'learned': 700,
 'simply': 564,
 'thirdly': 42,
 'ruined': 37,
 'sure': 958,
 'embarrasing': 5,
 'picture': 820,
 'forever': 280,
 'thus': 114,
 'lose': 408,
 'whether': 496,
 'addict': 21,
 'ruin': 123,
 'often': 597,
 'fault': 137,
 'enjoy': 902,
 'fall': 286,
 'ignore': 123,
 'numerous': 100,
 'rate': 125,
 'encourage': 63,
 'decrease': 53,
 "'percent": 4,
 'complicated': 28,
 'eye': 1896,
 'coordination': 800,
 'faraway': 265,
 'important': 1793,
 'strong': 640,
 'looking': 1105,
 'screen': 350,
 'moving': 318,
 'mouse': 107,
 'mostly': 313,
 'play': 1484,
 'sport': 402,
 'baseball': 110,
 'element': 133,
 'stronger': 144,
 'feild': 9,
 'taking': 1193,
 'note': 154,
 'involved': 138,
 'poor': 109,
 'else': 1227,
 'function': 53,
 'properly': 46,
 'doctor': 398,
 'healthy': 332,
 'travel': 281,
 'science': 126,
 'updated': 49,
 'culture': 798,
 'tradition': 71,
 'ignorant': 35,
 'remember': 764,
 'broke': 156,
 'either': 500,
 'made': 3071,
 'answering': 13,
 'happens': 280,
 'employee': 26,
 'co': 38,
 'leave': 624,
 'desk': 83,
 'faster': 379,
 'opposed': 21,
 'critical': 19,
 'reader': 1033,
 'dramatic': 19,
 'human': 404,
 'changed': 386,
 'device': 139,
 'provides': 79,
 'entertainment': 330,
 'quality': 103,
 'everyones': 48,
 'imagine': 240,
 'look': 2432,
 'refrigerator': 2,
 'notice': 169,
 'empty': 121,
 'grocery': 46,
 'shopping': 120,
 'food': 655,
 'ther': 112,
 'deal': 433,
 'company': 236,
 'deliver': 20,
 'free': 434,
 'amazing': 343,
 'leaving': 357,
 'purchase': 66,
 'product': 116,
 'sold': 65,
 'toy': 92,
 'hat': 56,
 'curtain': 13,
 'room': 1165,
 'item': 567,
 'relative': 377,
 'dose': 76,
 'call': 616,
 'anyone': 841,
 'adress': 14,
 'ease': 60,
 'boom': 27,
 'instant': 204,
 'face': 1253,
 'matter': 995,
 'watching': 568,
 'movie': 4525,
 'comfort': 243,
 'listing': 15,
 'music': 3591,
 'probable': 13,
 'popular': 163,
 'selection': 70,
 'fled': 3,
 'atleast': 72,
 'enjoyable': 104,
 'educational': 227,
 'produce': 28,
 'hate': 198,
 'revolutinizing': 1,
 'exciting': 76,
 'couple': 427,
 'extravagant': 4,
 'blow': 123,
 'mind': 951,
 'accomplish': 66,
 "'location": 12,
 'disagree': 247,
 'obesity': 168,
 'cramp': 12,
 'sexual': 184,
 'harrassment': 6,
 'cyber': 58,
 'bullying': 76,
 'watch': 1415,
 'entire': 273,
 'started': 1703,
 'pound': 71,
 'gain': 178,
 'weight': 724,
 'next': 1746,
 'top': 1885,
 'hear': 731,
 'teen': 484,
 'come': 3246,
 'straight': 155,
 'night': 577,
 'likely': 339,
 'fast': 508,
 'trying': 1404,
 'decide': 273,
 'anywhere': 208,
 'harassment': 4,
 'goin': 40,
 'mad': 517,
 'pissed': 8,
 'parent': 5915,
 'third': 355,
 'huge': 521,
 'cyberbullying': 12,
 'bully': 39,
 'realized': 694,
 'became': 437,
 'killed': 121,
 'stupid': 175,
 'god': 67,
 'cyberbullied': 5,
 'smart': 119,
 'enough': 1276,
 'money': 1127,
 'normally': 106,
 'occures': 1,
 'become': 1031,
 'act': 313,
 'big': 1326,
 'joke': 550,
 'turn': 771,
 'rot': 10,
 'little': 2180,
 'brain': 226,
 'horrible': 194,
 'acknowledge': 9,
 'disadvantage': 33,
 'known': 277,
 'develop': 72,
 'health': 385,
 'issue': 683,
 'intune': 1,
 'tend': 117,
 'forget': 752,
 'danger': 297,
 'deadly': 29,
 'television': 183,
 'refered': 2,
 'cauch': 2,
 'potato': 24,
 'glued': 36,
 'stated': 325,
 'spent': 345,
 'damage': 124,
 'highly': 764,
 'stressed': 60,
 'storm': 38,
 'submerge': 1,
 'depression': 46,
 'sink': 52,
 'addition': 197,
 'serious': 232,
 'surprised': 66,
 'wing': 25,
 'rehab': 4,
 'center': 59,
 'sometime': 99,
 'near': 233,
 'problem': 2751,
 'slowly': 185,
 'abolish': 4,
 'treasured': 5,
 'value': 94,
 'lately': 28,
 'ruining': 35,
 'absorbed': 6,
 'drama': 66,
 'video': 870,
 'interaction': 103,
 'declining': 3,
 'remove': 730,
 'reality': 257,
 'enter': 72,
 'alternate': 5,
 'cyberspace': 4,
 'emerge': 3,
 'bathroom': 194,
 'eat': 411,
 'scarcely': 3,
 'resting': 9,
 'tension': 61,
 'sorrow': 32,
 'erase': 9,
 'horrifying': 11,
 'story': 4701,
 'abduction': 3,
 'memory': 730,
 'dangerous': 579,
 'extremely': 400,
 'clever': 9,
 'console': 9,
 'forty': 48,
 'old': 1784,
 'serial': 3,
 'killer': 13,
 'waiting': 1034,
 'attack': 48,
 'fourth': 50,
 'user': 113,
 'encounter': 65,
 'x': 15124,
 'factor': 208,
 'obease': 11,
 'lack': 577,
 'realize': 412,
 'warming': 62,
 'becomeing': 8,
 'problum': 2,
 'socioty': 2,
 'cumputers': 2,
 'part': 1248,
 'basicly': 23,
 'couch': 112,
 'amarica': 3,
 'shape': 139,
 'habbit': 10,
 'addiction': 88,
 'exersise': 44,
 'computeres': 4,
 'mealting': 1,
 'polar': 4,
 'ice': 139,
 'electricty': 1,
 'thjen': 1,
 'electrisity': 3,
 'melt': 472,
 'happining': 4,
 'shorline': 1,
 'half': 501,
 'fluded': 1,
 'instance': 209,
 'splitting': 5,
 'sientest': 1,
 'sat': 534,
 'technolagy': 1,
 'peroson': 1,
 'themselfs': 23,
 'split': 41,
 'conclution': 21,
 'causeing': 3,
 'eventually': 326,
 'goung': 1,
 'flood': 11,
 'earth': 99,
 'unhappy': 40,
 'raed': 1,
 'ur': 26,
 'argument': 149,
 'reson': 52,
 'mane': 7,
 'cuzin': 1,
 'califan': 1,
 'wed': 7,
 'second': 1092,
 'stuck': 187,
 'plane': 173,
 'vary': 56,
 'boring': 233,
 'start': 1640,
 'exirsis': 1,
 'chart': 16,
 'run': 514,
 'meny': 12,
 'mile': 390,
 'sometimes': 1014,
 'thrid': 6,
 'peolpe': 15,
 'exmple': 1,
 'artical': 9,
 'didnt': 241,
 'writer': 185,
 'harder': 365,
 'whe': 25,
 'thinking': 540,
 'adout': 4,
 'agen': 6,
 'plea': 15,
 'consiter': 1,
 'thrie': 2,
 'resons': 26,
 "'three": 11,
 'detaileds': 1,
 'seconde': 2,
 'detailed': 26,
 'persuade': 31,
 'yor': 10,
 'postition': 3,
 'three': 831,
 'bigin': 2,
 'wast': 22,
 'fat': 134,
 'insted': 41,
 'girlfriend': 93,
 'incomputer': 1,
 'wach': 16,
 'stuff': 1055,
 'adult': 1436,
 'shod': 2,
 'becasue': 56,
 'air': 1374,
 'ba': 6,
 'porn': 29,
 'mainly': 125,
 'futur': 3,
 'addicted': 244,
 'mids': 2,
 'ganes': 1,
 'organize': 35,
 'present': 260,
 'clearly': 246,
 'plat': 3,
 'exersus': 1,
 'abd': 4,
 'cmputer': 3,
 'relly': 12,
 'staff': 41,
 'evrye': 1,
 'papaer': 3,
 'ols': 1,
 'se': 20,
 'useing': 53,
 'allow': 1869,
 'biggest': 241,
 'knowledge': 551,
 'zap': 1,
 'front': 623,
 'young': 1058,
 'ten': 302,
 'putting': 266,
 'thers': 3,
 'webchat': 10,
 'webcame': 4,
 'touch': 484,
 'blinked': 3,
 'image': 169,
 'blonde': 21,
 'haired': 7,
 'filled': 571,
 'thanks': 222,
 'actual': 61,
 'explaining': 111,
 'priceless': 18,
 'interection': 1,
 'nessessity': 1,
 'soceity': 10,
 'wish': 202,
 'expand': 63,
 'supported': 27,
 'firstly': 64,
 'usod': 1,
 'excel': 16,
 'felt': 862,
 'improves': 21,
 'simple': 745,
 'tying': 16,
 'build': 317,
 'famous': 127,
 'neurologist': 1,
 'week': 590,
 'strength': 267,
 'automatically': 33,
 'process': 146,
 'command': 8,
 'basketball': 119,
 'wa': 28,
 'decreasing': 10,
 'additionaly': 2,
 'search': 382,
 'presented': 51,
 'link': 47,
 'countless': 101,
 'peole': 30,
 'increase': 132,
 'tolerance': 15,
 'resourceful': 10,
 'aspect': 141,
 'bring': 522,
 'term': 97,
 'happend': 72,
 'citizen': 187,
 'cut': 283,
 'expensive': 102,
 'bill': 210,
 'pay': 368,
 'scaresly': 1,
 'visit': 227,
 'within': 266,
 'oviously': 1,
 'aid': 46,
 'era': 26,
 'advancement': 52,
 'push': 124,
 'foreward': 2,
 'handeye': 10,
 'bility': 1,
 'technologicall': 1,
 'sectored': 1,
 'unified': 10,
 'scare': 44,
 'nobody': 254,
 'slower': 41,
 'palce': 4,
 'belive': 168,
 'unhealthy': 140,
 'score': 53,
 'beauty': 82,
 'waste': 232,
 'privalges': 1,
 ...}

In [ ]:
maximum_frequency = max(word_frequencies.values())
maximum_frequency

36521

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
cv.fit_transform(df['essay']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer(smooth_idf=False,max_features=5000,ngram_range=(1,3))

doc_vector = tfid.fit_transform(df['essay'])
tf= pd.DataFrame(doc_vector.todense(),columns=tfid.get_feature_names())
tf

       abandoned   ability  ability to  ...  your own  your time  yourself
0            0.0  0.000000    0.000000  ...       0.0        0.0       0.0
1            0.0  0.000000    0.000000  ...       0.0        0.0       0.0
2            0.0  0.000000    0.000000  ...       0.0        0.0       0.0
3            0.0  0.036875    0.037843  ...       0.0        0.0       0.0
4            0.0  0.072805    0.074715  ...       0.0        0.0       0.0
...          ...       ...         ...  ...       ...        ...       ...
12971        0.0  0.000000    0.000000  ...       0.0        0.0       0.0
12972        0.0  0.000000    0.000000  ...       0.0        0.0       0.0
12973        0.0  0.000000    0.000000  ...       0.0        0.0       0.0
12974        0.0  0.000000    0.000000  ...       0.0        0.0       0.0
12975        0.0  0.000000    0.000000  ...       0.0        0.0       0.0

[12976 rows x 5000 columns]

In [ ]:
tfid.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': False,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [ ]:
x=cv.fit_transform(df['essay']).toarray()
y=df['domain1_score']

In [ ]:
y.head()

0     8
1     9
2     7
3    10
4     8
Name: domain1_score, dtype: int64

In [ ]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
y.shape

(12976,)

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/test_set.tsv",sep='\t', encoding='ISO-8859-1')

In [ ]:
df1.head()

   essay_id  essay_set  ... domain1_predictionid  domain2_predictionid
0      2383          1  ...                 2383                   NaN
1      2384          1  ...                 2384                   NaN
2      2385          1  ...                 2385                   NaN
3      2386          1  ...                 2386                   NaN
4      2387          1  ...                 2387                   NaN

[5 rows x 5 columns]

In [ ]:
df1.shape

(4254, 5)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4254 entries, 0 to 4253
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   essay_id              4254 non-null   int64
 1   essay_set             4254 non-null   int64
 2   essay                 4254 non-null   object
 3   domain1_predictionid  4254 non-null   int64
 4   domain2_predictionid  600 non-null    float64
dtypes: float64(1), int64(3), object(1)
memory usage: 166.3+ KB

In [ ]:
df1.describe()

           essay_id    essay_set  domain1_predictionid  domain2_predictionid
count   4254.000000  4254.000000           4254.000000            600.000000
mean   11922.108134     4.146685          14460.824636           8378.000000
std     6182.143429     2.132264           6896.586714            346.698716
min     2383.000000     1.000000           2383.000000           7779.000000
25%     5847.250000     2.000000           8716.500000           8078.500000
50%    11605.500000     4.000000          14605.500000           8378.000000
75%    17475.750000     6.000000          20475.750000           8677.500000
max    22242.000000     8.000000          25242.000000           8977.000000

In [ ]:
df1.isnull().sum()

essay_id                   0
essay_set                  0
essay                      0
domain1_predictionid       0
domain2_predictionid    3654
dtype: int64

In [ ]:
df1.dropna(axis = 1, inplace = True)

In [ ]:
df1.head()

   essay_id  ...  domain1_predictionid
0      2383  ...                  2383
1      2384  ...                  2384
2      2385  ...                  2385
3      2386  ...                  2386
4      2387  ...                  2387

[5 rows x 4 columns]

In [ ]:
df['essay']

0        Dear local newspaper, I think effects computer...
1        Dear @CAPS1 @CAPS2, I believe that using compu...
2        Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...
3        Dear Local Newspaper, @CAPS1 I have found that...
4        Dear @LOCATION1, I know having computers has a...
                               ...
12971     In most stories mothers and daughters are eit...
12972     I never understood the meaning laughter is th...
12973    When you laugh, is @CAPS5 out of habit, or is ...
12974                                   Trippin' on fen...
12975     Many people believe that laughter can improve...
Name: essay, Length: 12976, dtype: object

In [ ]:
df1_words = df1['essay'].apply(sent_tokenize)
df1_words.head()

0    [I believe that computers have a positive effe...
1    [Dear @CAPS1, I know some problems have came u...
2    [Dear to whom it @MONTH1 concern, Computers ar...
3    [Dear @CAPS1 @CAPS2, @CAPS3 has come to my att...
4    [Dear Local newspaper, I think that people hav...
Name: essay, dtype: object

In [ ]:
df1_words = df1['essay'].apply(word_tokenize)
df1_words.head()

0    [I, believe, that, computers, have, a, positiv...
1    [Dear, @, CAPS1, ,, I, know, some, problems, h...
2    [Dear, to, whom, it, @, MONTH1, concern, ,, Co...
3    [Dear, @, CAPS1, @, CAPS2, ,, @, CAPS3, has, c...
4    [Dear, Local, newspaper, ,, I, think, that, pe...
Name: essay, dtype: object

In [ ]:
nltk.download('wordnet')
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
from nltk.stem import WordNetLemmatizer
ps = WordNetLemmatizer()
corpus1 = []
for i in range(0, len(df1_words)):
    review = re.sub('[^a-zA-Z]', ' ', str(df1_words[i]))
    review = review.lower()
    review = review.split()
    review = [ps.lemmatize(word) for word in review if not word in stopwords.words('english')] 
    review = ' '.join(review)
    corpus1.append(review)

In [ ]:
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english') # To find list of stop words of english

words_frequencies = {}

for word in nltk.word_tokenize(str(corpus1)):
    if word not in stopwords:
        if word not in words_frequencies.keys():
            words_frequencies[word] = 1
        else:
            words_frequencies[word]+=1

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
max_frequency = max(words_frequencies.values())
max_frequency

12299

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
cv.fit_transform(df1['essay']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfids = TfidfVectorizer(smooth_idf=False)

doc_vector = tfids.fit_transform(df1['essay'])
tfs= pd.DataFrame(doc_vector.todense(),columns=tfids.get_feature_names())
tfs

       00  046  101st  102  102nd  ...  zoom  zooming  zooooooooom   zu  zuruck
0     0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
1     0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
2     0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
3     0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
4     0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
...   ...  ...    ...  ...    ...  ...   ...      ...          ...  ...     ...
4249  0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
4250  0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
4251  0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
4252  0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0
4253  0.0  0.0    0.0  0.0    0.0  ...   0.0      0.0          0.0  0.0     0.0

[4254 rows x 20721 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,  x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [ ]:
x_train.shape

(8693, 5000)

In [ ]:
x_test.shape

(4283, 5000)

In [ ]:
y_train

7737      2
1257      8
1920      4
8480      2
4832      1
         ..
4859      1
3264      5
9845      3
10799    22
2732      3
Name: domain1_score, Length: 8693, dtype: int64

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'normalize': [True, False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(x,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(x,y)

               model  best_score                               best_params
0  linear_regression    0.697744                      {'normalize': False}
1              lasso    0.755707       {'alpha': 1, 'selection': 'random'}
2      decision_tree    0.868272  {'criterion': 'mse', 'splitter': 'best'}

In [ ]:
## LSTM Modeling

## LSTM Modeling

In [71]:
#

In [70]:
from keras.layers import Embedding, LSTM, Dense, Dropout, Lambda, Flatten
from keras.models import Sequential, load_model, model_from_config
import keras.backend as K

def get_model():
    """Define the model."""
    model = Sequential()
    model.add(LSTM(300, dropout=0.4, recurrent_dropout=0.4, input_shape=[1, 300], return_sequences=True))
    model.add(LSTM(64, recurrent_dropout=0.4))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='relu'))

    model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['mae'])
    model.summary()

    return model

In [72]:
model

In [82]:

lstm_model = get_model()
lstm_model.fit(x_train, y_train, batch_size=64, epochs=2)
#lstm_model.load_weights('./model_weights/final_lstm.h5')
y_pred = lstm_model.predict(testDataVecs)

WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_4 (LSTM)                (None, 1, 300)            721200
_________________________________________________________________
lstm_5 (LSTM)                (None, 64)                93440
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65
=================================================================
Total params: 814,705
Trainable params: 814,705
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2

ValueError: ignored

In [83]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [84]:
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(100,1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')

In [85]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_6 (LSTM)                (None, 100, 50)           10400
_________________________________________________________________
lstm_7 (LSTM)                (None, 100, 50)           20200
_________________________________________________________________
lstm_8 (LSTM)                (None, 50)                20200
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51
=================================================================
Total params: 50,851
Trainable params: 50,851
Non-trainable params: 0
_________________________________________________________________

In [86]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_6 (LSTM)                (None, 100, 50)           10400
_________________________________________________________________
lstm_7 (LSTM)                (None, 100, 50)           20200
_________________________________________________________________
lstm_8 (LSTM)                (None, 50)                20200
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51
=================================================================
Total params: 50,851
Trainable params: 50,851
Non-trainable params: 0
_________________________________________________________________

In [92]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [93]:
y_test

10823    15
11018    17
2263      4
11074    20
12491    33
         ..
9702      4
3177      4
7759      2
9043      2
456       8
Name: domain1_score, Length: 4283, dtype: int64

In [94]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,batch_size=64,verbose=1)

Epoch 1/100

ValueError: ignored